ci: update workflow

diff --git a/.github/workflows/ci-pull-request.yml b/.github/workflows/ci-pull-request.yml
--- a/.github/workflows/ci-pull-request.yml
+++ b/.github/workflows/ci-pull-request.yml
@@ -3,6 +3,10 @@ name: Create Pull Request
 on:
   workflow_call:
     inputs:
+      source-branch:
+        description: Source branch
+        type: string
+        required: true
       target-branch:
         description: Target branch
         type: string
@@ -22,6 +26,35 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+
+    - name: Create branch
+      run: |
+        REPO="${{ github.repository }}"
+        BRANCH="${{ github.event.inputs.target-branch }}"
+        BASE="${{ github.event.inputs.source-branch }}"
+
+        echo "Checking if branch '$BRANCH' exists in repository '$REPO'..."
+
+        if gh api "repos/$REPO/branches/$BRANCH" --silent >/dev/null 2>&1; then
+            echo "Branch '$BRANCH' already exists."
+        else
+          echo "Branch '$BRANCH' does not exist. It will be created from '$BASE'."
+
+          BASE_SHA=$(gh api "repos/$REPO/git/ref/heads/$BASE" --jq .object.sha)
+
+          if [ -z "$BASE_SHA" ]; then
+            echo "Error: Could not retrieve the SHA of base branch '$BASE'"
+            exit 1
+          fi
+
+          gh api --method POST "repos/$REPO/git/refs" \
+            -f ref="refs/heads/$BRANCH" \
+            -f sha="$BASE_SHA"
+
+          echo "Branch '$BRANCH' successfully created!"
+        fi
+      env:
+        GH_TOKEN: ${{ github.token }}
 
     - name: Create Pull Request (${{ inputs.type }})
       uses: peter-evans/create-pull-request@v7
